# Generated by Django 3.0.7 on 2020-06-09 12:27

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200609_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]