# Generated by Django 3.0.7 on 2020-06-13 16:22

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
       ('menu', '0003_auto_20200613_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]