# Generated by Django 3.0.7 on 2020-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200609_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
