# Generated by Django 3.0.7 on 2020-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200609_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='amount',
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
