# Generated by Django 3.0.7 on 2020-06-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200611_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Pizza')),
            ],
        ),
    ]
