# Generated by Django 3.0.7 on 2020-06-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='size',
        ),
    ]
