# Generated by Django 3.0.7 on 2020-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20200612_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
