# Generated by Django 3.0.7 on 2020-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_pizza_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
